# Workflow for testing the api

name: API CI

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "README.md"
      - "LICENSE"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "README.md"
      - "LICENSE"

jobs: 
  test:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      - name: Setting up Nodejs
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x

      - name: Installing Dependencies
        run: |
          npm ci
      - name: Eslint
        run: |
          npm run lint
      - name: Jest
        run: |
          npm run test
      # - name: Upload Codecov
      #   run: |
      #     bash <(curl -s https://codecov.io/bash)