# Workflow for testing the api

name: API CI

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "README.md"
      - "LICENSE"
    tags:
      - "v*"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "README.md"
      - "LICENSE"

jobs: 
  test:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      - name: Setting up Nodejs
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x

      - name: Installing Dependencies
        run: |
          npm ci
      - name: Eslint
        run: |
          npm run lint
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: "4.4"
      - name: Jest
        run: |
          npm run test
      # - name: Upload Codecov
      #   run: |
      #     bash <(curl -s https://codecov.io/bash)
  docker:
    name: Push Docker image to registry
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' && (github.ref == 'refs/heads/master' || github.ref == 'refs/tags/v*') }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: azorimor/wekanchatbot
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64